[platformio]
src_dir = src

[env]
platform = atmelavr
framework = arduino
build_flags =
  -Os
  -ffunction-sections
  -fdata-sections

build_src_filter = +<*>

[env:uno]
board = uno
build_flags =
  ${env.build_flags}
  -DBOARD_UNO
  -DPIO_FRAMEWORK_ARDUINO_NO_MAIN

